language: csharp
mono: latest
dotnet: 2.0.0
dist: trusty

solution: PCLExt.FileStorage.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore PCLExt.FileStorage.sln
  
script:
  - dotnet restore src/PCLExt.FileStorage.Standard.Abstractions
  - dotnet restore src/PCLExt.FileStorage.Core
  - dotnet restore src/PCLExt.FileStorage.NetFX
  - dotnet restore test/PCLExt.FileStorage.Core.Test
  - dotnet restore test/PCLExt.FileStorage.NetFX.Test
  - dotnet build src/PCLExt.FileStorage.Standard.Abstractions
  - dotnet build src/PCLExt.FileStorage.Core
  - FrameworkPathOverride=/usr/lib/mono/4.5/ dotnet build src/PCLExt.FileStorage.NetFX
  - dotnet build test/PCLExt.FileStorage.Core.Test
  - FrameworkPathOverride=/usr/lib/mono/4.5/ dotnet build test/PCLExt.FileStorage.NetFX.Test
  - dotnet run test/PCLExt.FileStorage.Core.Test/PCLExt.FileStorage.Core.Test.csproj
  - FrameworkPathOverride=/usr/lib/mono/4.5/ dotnet run test/PCLExt.FileStorage.NetFX.Test/PCLExt.FileStorage.NetFX.Test.csproj

notifications:
  email:
    on_success: always
