language: csharp
mono: latest
dotnet: 2.0.0
dist: trusty

solution: PCLExt.FileStorage.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore PCLExt.FileStorage.sln
  
script:
  - dotnet restore
  - dotnet build
  - xbuild /p:Configuration=Release PCLExt.FileStorage.sln
  - xbuild /p:Configuration=Debug PCLExt.FileStorage.sln

notifications:
  email:
    on_success: always
