os: Visual Studio 2017

configuration:
- Debug
- Release
platform: Any CPU

install:
- git submodule update --init --recursive

before_build:
- nuget restore

build:
  project: PCLExt.FileStorage.sln
  verbosity: minimal
  
before_test:
- cmd: xcopy "C:\projects\pclext-filestorage\test\PCLExt.FileStorage.Core.Test\bin\Debug\netcoreapp2.0" "C:\projects\pclext-filestorage\test\PCLExt.FileStorage.Core.Test\bin\Any CPU\Debug\netcoreapp2.0" /S /I
