########################################################
##               MASTER                               ##
########################################################
-
  branches:
    only:
      - master-test

  os: Visual Studio 2017   
  configuration:
    - Debug
    - Release
  platform: Any CPU
  version: 1.4.1
  
  skip_commits:
    files:
      - docs/*
      - LICENSE
      - README.md
      - .travis.yml
      - .gitignore
      
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  
  environment:
    COVERALLS_REPO_TOKEN:  
       secure: q5xCVqG+/0ByXEFTGYgf1lCWwrOqq35br6CzLf5MPKMD2L8VboA10tKcRfW2n/70
    op_build_user: "OpenPublishBuild"
    op_build_user_email: "vscopbld@microsoft.com"
    access_token:
      secure: GQ3IuQcROfrBh1zCm97nDduFgUcaK9uD4xbawJx5iKcx5IvP7dEahe16nmwF+fQE

  artifacts:
    - path: "common\PCLExt.FileStorage.nupkg"
    
  assembly_info:
    patch: true
    file: common\CommonAssemblyInfo.cs
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
           
  init:
    - ps: |
        if ($env:APPVEYOR_REPO_TAG -eq "true")
        {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME)"
        }
    
  install:
    - git submodule update --init --recursive
  
  before_build:
    - nuget restore
    - ps: ./before_build_docfx.ps1
      on:
        configuration: Release
      
  build:
    project: PCLExt.FileStorage.sln
    verbosity: minimal
    
  after_build:
    - ps: ./after_build_docfx.ps1
      on:
        configuration: Release

  after_test:
    - ps: ./after_test_fx_core.ps1
    - ps: ./after_test_nuget.ps1
      on:
        configuration: Release
        

  deploy:
    provider: NuGet
    api_key:
      secure: yoZtG3i28wVuNDk1HrGW/t3tsgt3Ru/Yk/y/sOzUHRc2WVZlynVdWSHK/Bp0uShJ
    skip_symbols: false
    artifact: "common\PCLExt.FileStorage.*.nupkg"
    on:
      configuration: Release
      APPVEYOR_REPO_TAG: true


########################################################
##               DEVELOPMENT                          ##
########################################################
-
  branches:
    only:
      - devel
       
  os: Visual Studio 2017
  configuration: 
  - Release
  - Debug
  platform: Any CPU
  version: 1.4.1.{build}
  
  skip_commits:
    files:
      - docs/*
      - LICENSE
      - README.md
      - .travis.yml
      - .gitignore
      
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  
  environment:
    COVERALLS_REPO_TOKEN:  
       secure: q5xCVqG+/0ByXEFTGYgf1lCWwrOqq35br6CzLf5MPKMD2L8VboA10tKcRfW2n/70
  
  artifacts:
    - path: "common\PCLExt.FileStorage-devel.*.nupkg"
    
  assembly_info:
    patch: true
    file: common\CommonAssemblyInfo.cs
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}-devel"
  
  install:
    - git submodule update --init --recursive
  
  before_build:
    - nuget restore
  
  build:
    project: PCLExt.FileStorage.sln
    verbosity: minimal
  
  after_test:
    - ps: ./after_test_fx_core.ps1
    - ps: ./after_test_nuget.ps1
      on:
        configuration: Release
  
  deploy:
    provider: NuGet
    api_key:
      secure: yoZtG3i28wVuNDk1HrGW/t3tsgt3Ru/Yk/y/sOzUHRc2WVZlynVdWSHK/Bp0uShJ
    skip_symbols: false
    artifact: "common\PCLExt.FileStorage-devel.*.nupkg"
    on:
      configuration: Release


########################################################
##               ANY OTHER BRANCH                     ##
########################################################
-
  os: Visual Studio 2017
  configuration: 
  - Release
  - Debug
  platform: Any CPU
  
  skip_commits:
    files:
      - docs/*
      - LICENSE
      - README.md
      - .travis.yml
      - .gitignore
      
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml

  install:
    - git submodule update --init --recursive
  
  before_build:
    - nuget restore
  
  build:
    project: PCLExt.FileStorage.sln
    verbosity: minimal
  
  after_test:
    - ps: ./after_test_fx_core.ps1