os: Visual Studio 2017

configuration:
- Debug
platform: Any CPU

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  COVERALLS_REPO_TOKEN:  
       secure: q5xCVqG+/0ByXEFTGYgf1lCWwrOqq35br6CzLf5MPKMD2L8VboA10tKcRfW2n/70

install:
- git submodule update --init --recursive

before_build:
- nuget restore

build:
  project: PCLExt.FileStorage.sln
  verbosity: minimal

after_test:
- choco install codecov
- dotnet tool install -g coveralls.net
- cd test\PCLExt.FileStorage.Core.Test
- dotnet add package coverlet.msbuild
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[NUnit*]*
- csmacnz.coveralls --opencover coverage.opencover.xml -r %COVERALLS_REPO_TOKEN%
- codecov -f "coverage.opencover.xml"
- cmd: .\tools\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage_netfx.xml -r %COVERALLS_REPO_TOKEN%
- cd ..\..
