# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:

- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'PCLExt.FileStorage.sln'
      feedsToUse: 'select'
      vstsFeed: '64f8d3b1-f404-4cbc-a41c-4812cc142aad'
  # - task: MSBuild@1
  #   inputs:
  #     solution: 'PCLExt.FileStorage.sln'
  #     platform: 'AnyCPU'
  #     configuration: 'Release'
  #     clean: true
  #     maximumCpuCount: true
  #     logProjectEvents: true
  #     createLogFile: true
  # - task: VSTest@2
  #   inputs:
  #     testSelector: 'testAssemblies'
  #     testAssemblyVer2: |
  #       **\*test*.dll
  #       !**\*TestAdapter.dll
  #       !**\obj\**
  #     searchFolder: '$(System.DefaultWorkingDirectory)'

#   - task: DotNetCoreCLI@2
#     displayName: Restore
#     inputs:
#       command: restore
#       projects: '$(Parameters.RestoreBuildProjects)'
# #Android
#   - task: XamarinAndroid@1
#     inputs:
#       projectFile: 'src/PCLExt.FileStorage.Android/PCLExt.FileStorage.Android.csproj'
#       configuration: 'Release'
#       createAppPackage: false
#       jdkOption: 'JDKVersion'
# #iOS
#   - task: XamariniOS@2
#     inputs:
#       solutionFile: 'src/PCLExt.FileStorage.iOS/PCLExt.FileStorage.iOS.sln'
#       configuration: 'Release'
#       packageApp: false
#       runNugetRestore: true
